spectaql:
  logoFile: ./static/images/logo.png
  faviconFile: ./static/images/favicon.ico

introspection:
  schemaFile: ./src/graphql/public/schema.graphql

info:
  title: GraphQL API Reference
  description: Welcome to the Galoy API reference!
  contact:
    name: Galoy developer community
    url: https://chat.galoy.io/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.staging.galoy.io/graphql
    description: Signet
    production: false
